- package.json
> feat: node config

- .editorconfig
- .eslintrc.js
- .github/pull_request_template.md
- .husky/commit-msg
- .vscode/settings.json
- commitlint.config.js
- package-lock.json
- package.json
Adicion de la configurción del Eslint, commit lint y husky.
> feat: add project config

- .eslintrc.js
- .prettierrc
- package-lock.json
- package.json
- src/app.ts
- tsconfig.json
> feat: :sparkles: add-express-y-prettier

- .eslintrc.js
- package.json
Tener instalado volta en su pc.
> feat: :sparkles: add-volta

- .editorconfig
- .eslintrc.js
- .github/pull_request_template.md
- .husky/commit-msg
- .prettierrc
- .vscode/settings.json
- commitlint.config.js
- package-lock.json
- package.json
- src/api/healthcheck/healthcheck.controller.ts
- src/api/healthcheck/index.ts
- src/app.ts
- src/config/express.ts
- src/routes.ts
- tsconfig.json
Se carga toda la configuración inicial del proyecto.
> feat: add set up project

- .editorconfig
- .eslintrc.js
- .github/pull_request_template.md
- .husky/commit-msg
- .prettierrc
- .vscode/settings.json
- commitlint.config.js
- package-lock.json
- package.json
- src/api/healthcheck/healthcheck.controller.ts
- src/api/healthcheck/index.ts
- src/app.ts
- src/config/express.ts
- src/routes.ts
- tsconfig.json
* feat: node config (#1)
* feat: add project config (#2)
* feat: :sparkles: add-express-y-prettier (#3)
* feat: :sparkles: add-volta (#4)
* feat: :sparkles: scaffolding-express (#5)
se agrega express y estructura de carpetas
---------
> feat: add set up project (#6)

- src/api/users/users.controller.ts
- src/api/users/users.service.ts
- src/api/users/users.type.ts
Solo chequeando algunas cosas para ver el funcionamiento de este CRUD, cambiados algunos req.body a req.params y agregué un type que al final no parece necesario. 
Sigue un "problem" en el user.service dentro de la función deleteUser con el "isActive: false". Igual compila y funciona la app.
> fix: :adhesive_bandage: changed some req.body to params and added a type

- src/api/vehicles/index.ts
- src/api/vehicles/vehicles.controller.ts
- src/api/vehicles/vehicles.service.ts
- src/api/vehicles/vehicles.type.ts
cambiar unos req.body a req.params y creé un type para crear vehiculos donde no sean obligatorios todos los campos.
Además cambie la ruta del borrado logico de patch de solo ":id" a "delete/:id"
Hacer operaciones CRUD con los vehiculos.
> fix: :adhesive_bandage: corrected-tested-vehicles-CRUD

- package-lock.json
- package.json
- prisma/migrations/20230615005237_add_users_column_password_lastname/migration.sql
- prisma/migrations/20230615005644_corrected_password_lastname_mandatory/migration.sql
- prisma/schema.prisma
- src/api/users/users.service.ts
- src/api/usersByRole/usersByRole.service.ts
- src/auth/utils/bcrypt.ts
Va la instlacion de bcrypt, junto con su archivo dentro de la carpeta utils, ademas de la utilizacion de esta libreria para encriptar las contraseñas de los usuarios.
Crear un nuevo usuario con el metodo post.
> feat: :sparkles: bcrypt-hashedPassword

- package-lock.json
- package.json
- src/auth/auth.controller.ts
slocuion a la importacion en el controlador de autenticacion
> fix: :bug: correxion del controlador de autenticacion

- prisma/seed.ts
- src/api/vehicles/vehicles.service.ts
[//]: <> (se agrega el seed de vehiculos)
> feat: :zap: seed vehiculos

- src/api/users/users.type.ts
- src/auth/auth.controller.ts
- src/auth/auth.types.ts
Se modifican los middleware para la validación de roles y token. 
Las pruebas se realizan en vivo con Andres y Federico, para probar en sus equipos, deben importar el middleware e implementarlo en cualquiera de los end ponit que se encuentran en los index.ts de cada API.
> feat: modify middlewres roles validation

- package.json
- prisma/seed.js
- tsconfig.json
> fix: build error

- package.json
- prisma/seed.js
- tsconfig.json
Solución fix para el npm run build
> fix: build error (#30)

- package-lock.json
- package.json
- src/auth/local/local.controller.ts
Agregado un console.log para manejo de errores y hehco update del paquete de prisma-client.
> feat: :package: update-prisma-client

- src/app.ts
- src/index.ts
- tsconfig.json
Va la configuracion igual a la realizada por Christian, en cualquier caso lo podemos cambiar.
En teoría ya solo sería empezar a hacer los tests.
> feat: :adhesive_bandage: add-testing-config-asChris

- package.json
- src/api/roles/roles.controller.test.ts
- src/app.ts
Hola señores solo corriendo el test con el unico archivo que había creado Andres, se identifica que hay una advertencia al final donde indica que hay algo que se queda ejecutando despues del test.
Cuando se agrega un nuevo test sale el error y no es posible ejecutar mas test.
Entonces, revise las modifcaciones que realizaste ayer en el PR y creaste el archivo index separando las funcionalidades para levantar el servidor, pero no borraste las lineas de codigo que queriamos separar en el archivo app (Cuando revise el PR no me percate, fallamos allí), entonces al final es como si no hicieramos ningun cambio.
> fix: :bug: modify server configuration in two files

- src/auth/local/local.controller.ts
Si al hacer el login el usuario no ha activado su cuenta no podrá ingresar.
Crear un usuario, no activar la cuenta y probar ingresar.
> feat: :safety_vest: add-isActive-in-login

- package-lock.json
- package.json
- src/api/payments/index.ts
- src/api/payments/payments.controller.ts
- src/routes.ts
Se agrega endpoint api/payments, funcionando correctamente.
Se debe probar en conjunto con el front end, desde la pagina de payment, se van a realizar algunos retoques a la parte visual del front para tener todo el ciclo listo para probar.
> feat: :sparkles: add endpoint payments stripe

- prisma/migrations/20230707054532_trips_modifications/migration.sql
- prisma/schema.prisma
- src/api/trips/trips.controller.ts
- src/api/trips/trips.service.ts
- src/api/trips/trips.type.ts
Cambié el esquema y agregué unos tipos para que la info de trips que por ahora se está enviando desde el front pueda ir creando un viaje sin estado que devuelve la distancia calculada y el precio total que sale de la distancia por el feebase del tipo de vehiculo. Así el front puede pintarlo y puede empezar a implementarse en el flujo de pago que le acompaña.
[//]: <> (Pasos necesarios para probar esta funcionalidad) 
mandar en postman a la ruta `  http://localhost:8080/api/trips`, una solicitud POST con el objeto:
```{
"pickUpLatitude": "4.653530788760972",
"pickUpLongitude": "-74.10981503793789",
"dropOffLatitude": …
```
> feat: :sparkles: calculated-Trip-delivered

- prisma/migrations/20230707173344_trip_address/migration.sql
- prisma/schema.prisma
- prisma/seed.ts
- src/api/trips/trips.controller.ts
- src/api/trips/trips.type.ts
se agregan los strings con la direccion para usabilidad junto a las coordenadas
> fix: trips fixed to have addres strings

- src/auth/local/local.controller.ts
se agrega id del usuario logeado
> Fix loggin profile

- src/api/trips/trips.type.ts
- src/api/vehicles/vehicles.service.ts
se agreeaga email a la data traida
> build: send driver email

- src/api/trips/trips.controller.ts
- src/api/trips/trips.type.ts
Ya se utiliza el clientID que llega desde el front-end, es breaking changhe porque cambia un tipo.
crear un trip desde el front-end y revisarlo con `npx prisma studio`, queda asociado al id del cliente.
En azul la creación de un viaje ya con otro usuario, en rojo las anteriores que estaba hardcodeado el id.
> feat: :sparkles: clientID-received-from-front

- prisma/schema.prisma
- src/api/trips/trips.controller.ts
- src/api/trips/trips.service.ts
- src/api/trips/trips.type.ts
- src/api/vehicles/vehicles.service.ts
al llamar el controlador de correos se actualizan el viaje como activo y su esta a Scheduled
> Feature integration eamail front back

- src/api/trips/index.ts
- src/api/trips/trips.controller.ts
- src/api/trips/trips.service.ts
se crean las busquyedas de los historicos de viajes para clientes y condutores
> Feature trips histpricos

- src/api/trips/index.ts
- src/api/trips/trips.controller.ts
Se realizan pequeñas modificaciones para que el enpoint encargado de actualizar el viaje cuando se realiza el pago y se envíe el correo al conductor, funcione correctamente con la información enviada desde el backend. 
> refactor: :recycle: modify some types in createTripEmailHandler

- src/api/trips/trips.controller.ts
se camabian los endopints de historico de viajes por cliente y por conductor para no traer las ids desde los params
> fix: fix endpoints of trips historics

- src/api/trips/trips.service.ts
se agregan joins a tablas de servicetype, users y vehichles para los servicios de historico de viaje segun id de cliento o de conductor
> fix: cambios a endopints para estructura de info

- src/api/trips/index.ts
- src/api/trips/trips.controller.ts
- src/api/trips/trips.service.ts
Se agrega nuevo end point para la actualización del estado de los trips
> feat: :sparkles: add new patch endpoint for table trips

- src/api/trips/trips.service.ts
se ordenan los viajes por fecha en orden descendente
> fix: tips sorted

- src/api/vehicles/index.ts
- src/api/vehicles/vehicles.controller.ts
- src/api/vehicles/vehicles.service.ts
se agrega cambio a disponibilidad del vehiculo segun estados del viaje
> build: fixex in trips flux

- src/api/vehicles/vehicles.controller.ts
Correccionrapida, nada que decirm,usamos params y no el boy para el id, ya.
> refactor: :recycle: changeID- body-2-Params

- src/api/trips/trips.controller.ts
> Hotfix mailtodriver

- src/api/vehicles/index.ts
- src/api/vehicles/vehicles.controller.ts
- src/api/vehicles/vehicles.service.ts
- src/api/vehicles/vehicles.type.ts
* build: fix mails to driver
* build: fix url
createVehicleWithImage
Faltan estilos pero ahora se puede subir imagenes apara el vehiculo
> createVehicleWithImage (#78)
